
import java.util.ArrayList;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Lucas Mendes
 */
public class InputFrame extends javax.swing.JFrame {

    /**
     * Creates new form InputFrame
     */
        Node root;
        BST bst = new BST();
    public InputFrame() {
        
        initComponents();
        
        /*
        //Arvore desbalanceada
        root = bst.insert(root,"noé");
        root = bst.insert(root,"lana");
        root = bst.insert(root,"alex");
        root = bst.insert(root,"eva");
        root = bst.insert(root,"mara");
        */
        
        /*
        //Arvore balanceada
        root = bst.insert(root, "noé");
        root = bst.insert(root, "lana");
        root = bst.insert(root, "alex");
        root = bst.insert(root, "mara");
        root = bst.insert(root, "pablo");
        root = bst.insert(root, "omar");
        root = bst.insert(root, "rui");
        */
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        InfoDialog = new javax.swing.JDialog();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sizeLabel = new javax.swing.JLabel();
        heightLabel = new javax.swing.JLabel();
        minElLabel = new javax.swing.JLabel();
        maxElLabel = new javax.swing.JLabel();
        internalPathLengthLabel = new javax.swing.JLabel();
        isBalancedLabel = new javax.swing.JLabel();
        travessiaDialog = new javax.swing.JDialog();
        jScrollPane1 = new javax.swing.JScrollPane();
        nomesTravessiaTextArea = new javax.swing.JTextArea();
        NameToAdd = new javax.swing.JTextField();
        AddNameBtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        fazerTravessiaBtn = new javax.swing.JButton();
        travessiaComboBtn = new javax.swing.JComboBox<>();
        showInfoBtn = new javax.swing.JButton();
        AddConfirmLabel = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        InfoDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        InfoDialog.setTitle("Informações sobre a arvore");
        InfoDialog.setLocation(new java.awt.Point(250, 250));
        InfoDialog.setMinimumSize(new java.awt.Dimension(500, 200));
        InfoDialog.setPreferredSize(new java.awt.Dimension(487, 169));

        jLabel2.setText("Tamanho:");

        jLabel3.setText("Altura:");

        jLabel4.setText("Menor elemento:");

        jLabel5.setText("Maior elemento:");

        jLabel6.setText("Comprimento interno:");

        jLabel8.setText("Está balanceada?");

        sizeLabel.setText(" ");

        heightLabel.setText(" ");

        minElLabel.setText(" ");

        maxElLabel.setText(" ");

        internalPathLengthLabel.setText(" ");

        isBalancedLabel.setText(" ");

        javax.swing.GroupLayout InfoDialogLayout = new javax.swing.GroupLayout(InfoDialog.getContentPane());
        InfoDialog.getContentPane().setLayout(InfoDialogLayout);
        InfoDialogLayout.setHorizontalGroup(
            InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE)
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(heightLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(isBalancedLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(internalPathLengthLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(maxElLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(minElLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        InfoDialogLayout.setVerticalGroup(
            InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(InfoDialogLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sizeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(heightLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(minElLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(maxElLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(internalPathLengthLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(InfoDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(isBalancedLabel))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        travessiaDialog.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        travessiaDialog.setMinimumSize(new java.awt.Dimension(400, 300));

        nomesTravessiaTextArea.setColumns(20);
        nomesTravessiaTextArea.setRows(5);
        jScrollPane1.setViewportView(nomesTravessiaTextArea);

        javax.swing.GroupLayout travessiaDialogLayout = new javax.swing.GroupLayout(travessiaDialog.getContentPane());
        travessiaDialog.getContentPane().setLayout(travessiaDialogLayout);
        travessiaDialogLayout.setHorizontalGroup(
            travessiaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        travessiaDialogLayout.setVerticalGroup(
            travessiaDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simple BST manager");
        setLocation(new java.awt.Point(250, 250));

        NameToAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameToAddActionPerformed(evt);
            }
        });
        NameToAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                VK_ENTER(evt);
            }
        });

        AddNameBtn.setText("Adicionar nome");
        AddNameBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNameBtnActionPerformed(evt);
            }
        });

        fazerTravessiaBtn.setText("Realizar travessia");
        fazerTravessiaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fazerTravessiaBtnActionPerformed(evt);
            }
        });

        travessiaComboBtn.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pré ordem", "Em ordem", "Pós ordem", "Em nivel" }));
        travessiaComboBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                travessiaComboBtnActionPerformed(evt);
            }
        });

        showInfoBtn.setText("Mostrar informações");
        showInfoBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInfoBtnMouseClicked(evt);
            }
        });
        showInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showInfoBtnActionPerformed(evt);
            }
        });

        jLabel7.setText("Nome");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NameToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(AddNameBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AddConfirmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(fazerTravessiaBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(travessiaComboBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(showInfoBtn)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(AddConfirmLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameToAdd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AddNameBtn))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(travessiaComboBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showInfoBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fazerTravessiaBtn)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NameToAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameToAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameToAddActionPerformed

    private void travessiaComboBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_travessiaComboBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_travessiaComboBtnActionPerformed

    private void showInfoBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showInfoBtnMouseClicked
        sizeLabel.setText(bst.size(root) + " Nós"); //Tamanho
        heightLabel.setText("" + bst.heigth(root)); //Altura
        minElLabel.setText(bst.minor(root));
        maxElLabel.setText(bst.greater(root));
        internalPathLengthLabel.setText("" + bst.InternalPathLength(root));
        String isBalanced = "Não";
        if(bst.isBalanced(root) == true){
            isBalanced = "Sim";
        }
        isBalancedLabel.setText(isBalanced);
        
        
        InfoDialog.setVisible(true);
    }//GEN-LAST:event_showInfoBtnMouseClicked

    private void showInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showInfoBtnActionPerformed

    }//GEN-LAST:event_showInfoBtnActionPerformed

    private void AddNameBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNameBtnActionPerformed
        //Pega o texto da label e adiciona na arvore
        String name = NameToAdd.getText();
        bst.insert(root,name);
        NameToAdd.setText("");
    }//GEN-LAST:event_AddNameBtnActionPerformed

    private void fazerTravessiaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fazerTravessiaBtnActionPerformed
        String travessiaSelecionada = travessiaComboBtn.getSelectedItem().toString();
        ArrayList <String> nomes = new ArrayList();
        if(root == null){
            nomes.add("A arvore está vazia");
        }
        if(travessiaSelecionada.equals("Pré ordem")){
            travessiaDialog.setTitle("Pré ordem");
            nomes = bst.preOrder(root);
        }
        else if(travessiaSelecionada.equals("Em ordem")){
            travessiaDialog.setTitle("Em ordem");
            nomes = bst.inOrder(root);
        }
        else if(travessiaSelecionada.equals("Pós ordem")){
            travessiaDialog.setTitle("Pós ordem");
            nomes = bst.postOrder(root);
        }
        else if(travessiaSelecionada.equals("Em nivel")){
            travessiaDialog.setTitle("Em nivel");
            nomes = bst.levelOrder(root);
        }
        nomesTravessiaTextArea.setText(""); //Limpa os nomes anteriores no textArea
        for (String nome : nomes){
            nomesTravessiaTextArea.append(nome + "\n");
        }
        travessiaDialog.setVisible(true);
        
            
        
        //comboBoxSelection.setText(travessiaSelecionada);
    }//GEN-LAST:event_fazerTravessiaBtnActionPerformed

    private void VK_ENTER(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_VK_ENTER

    }//GEN-LAST:event_VK_ENTER

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddConfirmLabel;
    private javax.swing.JButton AddNameBtn;
    private javax.swing.JDialog InfoDialog;
    private javax.swing.JTextField NameToAdd;
    private javax.swing.JButton fazerTravessiaBtn;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JLabel internalPathLengthLabel;
    private javax.swing.JLabel isBalancedLabel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel maxElLabel;
    private javax.swing.JLabel minElLabel;
    private javax.swing.JTextArea nomesTravessiaTextArea;
    private javax.swing.JButton showInfoBtn;
    private javax.swing.JLabel sizeLabel;
    private javax.swing.JComboBox<String> travessiaComboBtn;
    private javax.swing.JDialog travessiaDialog;
    // End of variables declaration//GEN-END:variables
}
